name: GitHub Pages CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: NPM CI
        run: npm ci

      - name: PWA Build
        run: npm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
          
      - name: Checkout Github Pages repository
        uses: actions/checkout@v3
        with:
          repository: PrimalZed/primalzed.github.io
          token: ${{ secrets.GH_PAGES_PAT }}
          path: pages
     
      - name: Copy dist to pages
        run: |
          rm -r -d -v pages/haven-keeper
          cp -r -v dist/haven-keeper pages/haven-keeper

     # Create and push commit
      # - run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "generated"
      #     git push
      #   working-directory: pages